#!/bin/bash


killall --user $USER --ignore-case --signal INT ffmpeg
notify-send "Screen recording starts now...."

DIR="$HOME/Videos/recording"

# Create the directory if it doesn't exist
if [ ! -d "$DIR" ]; then
  mkdir -p "$DIR"
fi

# low quality capture
#
#
date="$(date +%B-%d-%Y_%H-%M-%S)"

### STABLE ONE 

# ffmpeg -f x11grab -framerate 60 -video_size $(xdpyinfo | grep 'dimensions:' | awk '{print $2}') -i "$(xdotool getactivewindow)" -c:v libx264 -preset faster -crf 18 -pix_fmt yuv420p -movflags +faststart -threads 8 -bufsize 5000k -tune zerolatency -y "$HOME/Videos/recording/rec-$(date +%B-%d-%Y_%H-%M-%S).mp4" &


## WITH AUDIO
ffmpeg -f x11grab -framerate 60 -video_size $(xdpyinfo | grep 'dimensions:' | awk '{print $2}') -i "$(xdotool getactivewindow)" -f pulse -i "$(pactl info | grep 'Default Source' | awk '{print $3}')" -c:v libx264 -preset faster -crf 18 -pix_fmt yuv420p -movflags +faststart -threads 8 -bufsize 5000k -tune zerolatency -y "$HOME/Videos/recording/rec-$(date +%B-%d-%Y_%H-%M-%S).mp4" &

